In [2]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
x,y =make_classification(n_samples=1000, n_features=10,n_redundant=5,n_informative=5,n_classes=2,random_state=1)

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.30, random_state=1)

In [6]:
#hyperparamatic tuning 
#grid serach cv
from sklearn.model_selection import GridSearchCV

In [7]:
params = {'penalty':('l1','l2','elasticnet'), 'C':[1,2,10,20,30,40]}

In [8]:
classifier = LogisticRegression()

In [9]:
clf =GridSearchCV(classifier, param_grid=params,cv=5)

In [10]:
import warnings
warnings.filterwarnings('ignore')

In [11]:
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 40],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [12]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [13]:
clf.best_score_

np.float64(0.8042857142857145)

In [14]:
model = LogisticRegression(C=1,penalty='l2')

In [15]:
model.fit(x_train,y_train)

LogisticRegression(C=1)

In [16]:
y_pred = model.predict(x_test)

In [17]:
model.predict_proba(x_test)

array([[0.01925457, 0.98074543],
       [0.8369654 , 0.1630346 ],
       [0.71163174, 0.28836826],
       [0.86595477, 0.13404523],
       [0.44881263, 0.55118737],
       [0.906619  , 0.093381  ],
       [0.03803546, 0.96196454],
       [0.69878052, 0.30121948],
       [0.87649197, 0.12350803],
       [0.04268774, 0.95731226],
       [0.91221239, 0.08778761],
       [0.57950286, 0.42049714],
       [0.27686074, 0.72313926],
       [0.76744489, 0.23255511],
       [0.41878562, 0.58121438],
       [0.33162756, 0.66837244],
       [0.05094872, 0.94905128],
       [0.14027377, 0.85972623],
       [0.02937625, 0.97062375],
       [0.92765479, 0.07234521],
       [0.55017835, 0.44982165],
       [0.04323274, 0.95676726],
       [0.18990573, 0.81009427],
       [0.89966296, 0.10033704],
       [0.09082865, 0.90917135],
       [0.44410569, 0.55589431],
       [0.85854528, 0.14145472],
       [0.5383565 , 0.4616435 ],
       [0.49035344, 0.50964656],
       [0.82655524, 0.17344476],
       [0.

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[129  13]
 [ 34 124]]
0.8433333333333334
              precision    recall  f1-score   support

           0       0.79      0.91      0.85       142
           1       0.91      0.78      0.84       158

    accuracy                           0.84       300
   macro avg       0.85      0.85      0.84       300
weighted avg       0.85      0.84      0.84       300



In [19]:
#randomized search cv  > it will take some combination 

In [20]:
from sklearn.model_selection import RandomizedSearchCV

In [21]:
rand =RandomizedSearchCV(classifier, param_distributions=params , cv=5 , n_iter=10)

In [22]:
rand.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 10, 20, 30, 40],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [23]:
rand.best_score_

np.float64(0.8042857142857145)

In [24]:
rand.best_params_

{'penalty': 'l2', 'C': 10}

In [25]:
model = LogisticRegression(C=20, penalty='l2')

In [26]:
model.fit(x_train,y_train)

LogisticRegression(C=20)

In [27]:
y_pred = model.predict(x_test)

In [28]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[129  13]
 [ 34 124]]
0.8433333333333334
              precision    recall  f1-score   support

           0       0.79      0.91      0.85       142
           1       0.91      0.78      0.84       158

    accuracy                           0.84       300
   macro avg       0.85      0.85      0.84       300
weighted avg       0.85      0.84      0.84       300



In [29]:
x,y =make_classification(n_samples=1000, n_features=10,n_redundant=5,n_informative=5,n_classes=3,random_state=1)

In [37]:
#ovr
model =LogisticRegression(multi_class='ovr',solver='lbfgs')

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.30, random_state=1)

In [36]:
x_train.shape,x_test.shape

((700, 10), (300, 10))

In [38]:
model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [40]:
y_pred = model.predict(x_test)

In [44]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[75 21  3]
 [10 58 21]
 [23 14 75]]
0.6933333333333334
              precision    recall  f1-score   support

           0       0.69      0.76      0.72        99
           1       0.62      0.65      0.64        89
           2       0.76      0.67      0.71       112

    accuracy                           0.69       300
   macro avg       0.69      0.69      0.69       300
weighted avg       0.70      0.69      0.69       300



In [45]:
#multinomial
model1 =LogisticRegression(multi_class='multinomial',solver='lbfgs')

In [47]:
model1.fit(x_train,y_train)

LogisticRegression(multi_class='multinomial')

In [48]:
y_pred = model1.predict(x_test)

In [49]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[70 21  8]
 [13 57 19]
 [21 13 78]]
0.6833333333333333
              precision    recall  f1-score   support

           0       0.67      0.71      0.69        99
           1       0.63      0.64      0.63        89
           2       0.74      0.70      0.72       112

    accuracy                           0.68       300
   macro avg       0.68      0.68      0.68       300
weighted avg       0.69      0.68      0.68       300



In [50]:
from sklearn.datasets import load_iris
data = load_iris()

In [52]:
import pandas as pd
import numpy as np
df = pd.DataFrame(data.data, columns = data.feature_names)
df['target'] = data.target

In [54]:
x = df.drop('target',axis=1)

In [55]:
y= df['target']

In [56]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=1)

In [58]:
x_train.shape,x_test.shape

((120, 4), (30, 4))

In [60]:
model = LogisticRegression(max_iter=300)

In [61]:
model.fit(x_train,y_train)

LogisticRegression(max_iter=300)

In [62]:
y_pred = model.predict(x_test)

In [63]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

